import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import Nav from '@/components/nav'
import '@/styles/Home.module.scss'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Nav />
      <div className={styles.container}>
        <Head>
          <title> VIT Conference </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>

      <main className={styles.main}>
        <div className={styles.logo}>
          <Image src="/logo.png" width={128} height={77} />
        </div>
        <div className={styles.title}>
          <h1> VIT Conference </h1>
        </div>
        <div className={styles.description}>
          <p> A conference for the students of VIT </p>
        </div>
        <div className={styles.button}>
          <button> Register Now </button>
        </div>
      </main>


    </>
  )
}
